version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: tennis_table
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d tennis_table"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: